spring.application.name=projectPi
spring.main.allow-bean-definition-overriding=true

spring.data.mongodb.uri=mongodb+srv://dalydevmosaiqueweb_db_user:9xJpftIJi8dzBf3I@cluster0.3bkqu0v.mongodb.net/projectPi?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true

### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

### Server Configuration ###
server.port=8081
server.servlet.context-path=/streetleague

### Springdoc OpenAPI 3.0 & Swagger UI Configuration ###
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.show-logo=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.display-request-duration=true
springdoc.use-fqn=false

